openapi: "3.0.0"
info:
  version: 1.0.0
  title: API-сервис пользователей
  description: |
    ## Предзарегистрированные пользователи:
    
    ### Админ:
    Email: **admin@usersapp.ru**<br>
    Password: **password**

    ### Рядовой пользователь:
    Email: **user@usersapp.ru**<br>
    Password: **password**
tags:
  - name: Users
    description: Операции с пользователями
  - name: Auth
    description: Аутентификация
paths:
  /auth/register:
    post:
      summary: Зарегистрировать пользователя
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              $ref: "#/components/schemas/RegisterRequestBody"
          application/json:
            schema:
              type: object
              $ref: "#/components/schemas/RegisterRequestBody"
      responses:
        "201":
          description: Пользователь успешно зарегистрирован
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/User"
        "400":
          description: Ошибочный запрос
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Error"
        "409":
          description: Конфликт входных данных
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Error"
        "422":
          description: Ошибка валидации
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/ValidationError"
      tags:
        - Auth

  /auth/login:
    post:
      summary: Залогинить пользователя
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              $ref: "#/components/schemas/LoginRequestBody"
          application/json:
            schema:
              type: object
              $ref: "#/components/schemas/LoginRequestBody"
      responses:
        "201":
          description: Пользователь успешно залогинен
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/LoginResponseBody"
        "401":
          description: Неверный почтовый адрес или пароль
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Error"
        "403":
          description: Ошибка доступа
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Error"
        "422":
          description: Ошибка валидации
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/ValidationError"

      tags:
        - Auth

  /auth/me:
    get:
      summary: Получение данных залогиненного пользователя
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Успешно
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/User"
      tags:
        - Auth

  /users:
    get:
      summary: Получить список пользователей
      description: Для получения списка пользователей требуется роль админа
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Успешно
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
        "401":
          description: Пользователь не прошел аутентификацию
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Error"
        "403":
          description: Ошибка доступа
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Error"
      tags:
        - Users

  /users/{userId}:
    parameters:
      - $ref: "#/components/parameters/UserIdParam"
    get:
      summary: Получить пользователя по ID
      description: Может получить либо админ, либо пользователь сам себя
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Успешно
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/User"
        "401":
          description: Пользователь не прошел аутентификацию
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Error"
        "403":
          description: Ошибка доступа
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Error"
        "404":
          description: Пользователен не найден
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Error"
        "422":
          description: Ошибка валидации
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/ValidationError"
      tags:
        - Users

  /users/{userId}/block:
    parameters:
      - $ref: "#/components/parameters/UserIdParam"
    post:
      summary: Заблокировать пользователя
      description: Может либо админ, либо пользователь сам себя
      security:
        - bearerAuth: []
      responses:
        "204":
          description: Пользователь успешно заблокирован
        "401":
          description: Пользователь не прошел аутентификацию
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Error"
        "403":
          description: Ошибка доступа
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Error"
      tags:
        - Users

components:
  parameters:
    UserIdParam:
      name: userId
      in: path
      required: true
      schema:
        type: integer
        minimum: 1
      description: "Идентификатор пользователя"
      example: 10
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          description: "Идентификатор пользователя"
          example: "42"
        full_name:
          type: string
          description: "ФИО пользователя в формате <Фамилия> <Имя> <Отчество>"
          example: "Иванов Иван Иванович"
        birth_date:
          type: string
          description: Дата рождения в формате DD.MM.YYYY
          example: "17.09.1984"
        email:
          type: string
          format: email
          description: Почтовый адрес
          example: "user@example.com"
        role:
          type: string
          enum: [admin, user]
          example: "user"
        active:
          type: boolean

    RegisterRequestBody:
      type: object
      required:
        - email
        - full_name
        - birth_date
        - password
      properties:
        email:
          $ref: "#/components/schemas/User/properties/email"
        full_name:
          $ref: "#/components/schemas/User/properties/full_name"
        birth_date:
          $ref: "#/components/schemas/User/properties/birth_date"
        password:
          description: Пароль
          type: string
          format: password
          example: "@2ptL3nF"

    LoginRequestBody:
      type: object
      required:
        - email
        - password
      properties:
        email:
          $ref: "#/components/schemas/RegisterRequestBody/properties/email"
        password:
          $ref: "#/components/schemas/RegisterRequestBody/properties/password"

    LoginResponseBody:
      type: object
      required:
        - user
        - token
      properties:
        user:
          type: object
          $ref: "#/components/schemas/User"
          description: Данные пользователя
        token:
          type: string
          description: Токен доступа для Bearer-аутентификации
          example: "eyJhbGciOiJIUzI1NiJ9.Mg.HSyZK7J99A_UrZoIJqAICgs0AKdS8T6RAJ0cpBPy7qM"
    Error:
      type: object
      properties:
        message:
          type: string
          description: Сообщение об ошибке
          example: Сообщение об ошибке
    FieldError:
      type: object
      properties:
        field:
          type: string
          description: Имя поля
          example: email
        message:
          type: string
          description: Сообщение об ошибке
          example: Поле обязательно для заполнения
    ValidationError:
      type: object
      properties:
        message:
          type: string
          description: Сообщение об ошибке
          example: Ошибка валидации
        errors:
          type: array
          items:
            $ref: "#/components/schemas/FieldError"
